apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ebmd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-ebmd@sha256:d898dd71d8e2c52a22339aa60344d3733b772f7406b6742db10e135589cffeb7
        name: my-nodejs
        resources: {}
status: {}
